fix: #304
vercel/satori pull request #310
Opened 2022-11-15 04:09 UTC by sahithyandev

2022-11-15 04:13 UTC, sahithyandev commented
Background image was not showing because of the image didn't resolve with a size.
Fixed by decoding the data URI (when its svg) and parsing it to find the image size.

2022-11-15 10:41 UTC, wei commented on src/handler/image.ts
> +        imageSize = parseSvgImageSize(src, atob(imageData))
data uris are not always in base64, are there ways to intelligently detect it?

e.g. 
[Valid data uri `data:image/svg+xml,...` <img width="1773" alt="image" src="https://user-images.githubusercontent.com/5880908/201897809-19ccd959-415f-46d0-8c01-43017c8a7467.png">](https://satori-playground-git-fork-sahithyandev-fix-background-i-7197fe.vercel.sh/?share=pVRbT9swFP4rllHEpjXGsXNpI0DaChE88DQkXvpASNzWzE2iJKUtVf_7znESVtikaZra2Mffd66-nD3NylzRmJ7n-mVWENK0O6Mu9nuUCVkqvVi2MTn1OHdORx240Xm7_IDluqlMugN0btR2QFG-0rXKWl0WwGWlWa-KgU2NXhS3rVo1SKmiVfVAPa-bVs930xLAAuO_p5_S7MeiLtdFPi1NWQN_Mp_P36KC1Xf9qmIixRH00NcScv6bm9tVugD9x3VtPuVpm8YagbPmZfFluzIjR05BdASHRdE48soRYtm2lSO_OiKB_2azYRvJyhqUEsFhY0RiLQQYvWi1-VZuOzNgkOUy7AfhyGvwX6XtEpC5NqZTdIRMkunU72Sed-idtfPGGfqYsInvuWPGg4kFXW_czUhgHAA6GgVvPEUjWKOLfkLEWvHMejuGepXeqU0j6ZJVxuiqUR_zDUM_QHPMN-vr9TwW9MiuR8SA1L3OL6BXCXrg38MJ___D_ekojmMNR2E3RojMlSwU0u53yLiIXOYL4cKeuyyMJi7zpOeiHbejleDDA4JkJxCa2-PDvUchZL4l7Tl4LvIwIQMOXI9JAe7AqYAV_NgkkiyIxm7AZBShstX1Xv9WUpLAzT2uB82EbLCSIRc7u_1o0_etdxhd-72L0l96ef35ER_Y4TArLlE4B_SodVzMaBTMaIf0jwMwTjiJAhK-UZgt4CfwnAZo6E5kldYLjS0FbartqQ1GiA0HAbFekoPxnYxgj5kIjAzZBLz7Nyz0u4Ub-q8zenl-htpdovjiOwna4cdo92UVE59DqMsbuJLliDyUtcnPz0AXjIaZjmhZYcNraLyntmIaj6Hp0K6b0tjHRa6e1gsaz1PTqBFVq_JZ3-8qbMXtxq7AD7at69WTymnc1mt1OPwE)

[Valid data uri `data:image/svg+xml;utf8,...` ](https://satori-playground-git-fork-sahithyandev-fix-background-i-7197fe.vercel.sh/?share=pVRbT9swFP4rkVHEpjXGsXNps4K0FSJ44GlIvPSBkDitmZtESUpbqv73neMkrLBJ04Ta2Mffd66-nD1Jy0ySiEwz9TwvLKtpd1qe7_coW9ZSqsWyjaxTlzH7dNSBG5W1y3dYpppKJztAcy23A4rypapl2qqyAC4t9XpVDGyi1aK4aeWqQUoWrawH6mndtCrfzUoAC4z_ln5M0p-LulwX2azUZQ38SZ7nr1HB6od6kZEl-BF039cSMPaHm5tVsgD9h3WtP2VJm0QKgbPmefFlu9Jf120-HtliBmubM0CKxhaXNufLtq1s8c3mMfw3mw3dCFrWoBRzBrvDY2PBwehZyc33ctuZAYMsE0E_cFtcgf8qaZeA5ErrTtHmIo5nM6-TWdaht8bOHafoY0InnuuMKfMnBnTccTcjgXEA6GgU3PEMjWCNLvoJEWPFUuPtGOpVeqcmjbhLVmqtqka-zzcIPB_NMd-0r9d1qd8jux7hA1L3Or-BXsXvgf8Px72Ph_vbURzHGo7CbAznqSNowIXZ74AyHjrU49yBPXdoEE4c6grXQTtmRiPBhwcEyU4gNDPHh3uPQkA9Q5pzcB3kYUIGHDguFRzcgVMOK_jRSSioH44dn4owRGWj6778q6Q4hpt7XA-acdFgJUMuZnb60aTvGe8wOuZ7E6W_9OLq8wO-ssNhXlygMAX0qH-cz0noz0mH9I8DMGYxK_St4JXCbAE_gec0QEOLslZJvVDYV9Cm2p6aYJZlwkFArNfKwPhWhLDHlPtaBHQC3r1rGnjdwgm8lzm5mJ6hdpcoPvtOgp74PtpdWUWWxyDUxTVcyXJk3Ze1zqZnoAtGw0xGpKyw6zUk2hNTMYnG0HlI11JJ5OEik4_rBYnyRDdyROSqfFJ3uwr7cbsxK_CDvetq9SgzErX1Wh4OvwA)

2022-11-15 10:47 UTC, wei requested changes
Thanks so much for the PR!! Works great on [svg](https://satori-playground-git-fork-sahithyandev-fix-background-i-7197fe.vercel.sh/?share=lVRbb6M4FP4riNGqu5ps6wZIp2xbiQCbUGGSFKo2KA9DwHFMuEQBwqXqf99jshnN7WHmAfn4O_6-czE-b2KYR0RUxbuIHVeZIBRlm5D7tzduC8KWMLotVeHiGqE_LgYnsGZRuf0Oi1ixT4IW0E1CmjPKbYMdSFiyPANfmCdVmp29QcJoZpUkLbiLZCU5nF1xVZRs0-o5gBmP_617HYQ7esirLNLzJD-A_8Nms_kSFVgu64gqSMOvoJf_axkh9IOMlQYUzn-uDsmfUVAGKuPAVXGkH5s0-WcdFGQkD-ZTZ-i3Y3n90lRhh1gwfUKhkR9tKZKiVpFwqxzDNDziWKuxfttFacisqb_3XyN9LdFbK9Yo1rXOYfyzPs6n4200odRPk2JtIGYhf7JAGD3pFvVh73l4aBmmvOw0OnNlxTHMcqbLtePtKPZoCV-_9j5dq23PlG2PVth4Vk62KS84l3OYJtuxBnqQA-dNsGLHO4RdreYxLIPzliefR5ndyZ_8l6YIXsed747TAOy5a8VOvESOBxw2jgnkiD2zclyLLqUd1Ge2dvwMNT_KcPZsK2Bfc_uXNePFb2mGk39RoP9Ubzd3H52-pvgxtj1cObHVQQ9Kh8k1jsPSjhctZoj3C-ylNHNRhT3c2J4Fd4Vay-CrhiwDcvJ215bBe2_CfWhD4Na879A_OP_McbgLfg9WiV25w7FZYiY3uIM9Qy3g1cwLO8hbmukI8seS02rABc3X_Ke1PO38ybkO0G6xBGpGH7-BXCCO1ueOmYa4jqPzWhaQB0KEWcd5XB9Dyc_m9P7-r8_8v39_X2UP3LiD3_urF32_Em-UlXhCjozU47wBDAlIuFGE0RfXhiUJ4B8QQmfoPDSENDhQxl865-ybiz6YIPThIOA-KLdCBGQs3Vwqt5dDJZFGl7egLk8vR_Jp8_dI7lbiw90VP31KlD_EkwVT6vtoXr5XBRlBqIcpSZJ8ILzkhyS6u4KzQDqv4kDM93wOFaL6JvYVi-onmAXiaciJqsw3EVlXVFQ3QVKQgUjSPGZeu-cTsqz7HejwaWKmaxKJanmoyPv7fw), [png](https://satori-playground-git-fork-sahithyandev-fix-background-i-7197fe.vercel.sh/?share=lVXZjqNGFP0Vy6OoE9EZFgM2Ts9IrDZ2g9kxVr9gs7gwZt9b_e-B7vRoMnlKSVCnzrm3TpUQ977OL6nnz9fzJw80L8lsVlZ97H97fZ3wbHb1QXit1rMHFEF-e3j8IFvgVddfOA-UWez2IxvEfvfJTpgDhX-pQJqM2iWN63vyqboxCBOx8u_lJPlJ5RefUlSXFQh6Nh3JZPL_t3x2L7ewSOvEY9M4LUb9SxAEP1zHLB0M_nq2wH6i7H_uQiLIf7YR7244xj_URfy751buGkwEnCXhX2e39En8EVjMQWuR_SZM6XHIunnlzXBE_PRiRJaWphlIiIxOAVeUkSze2l74AR74xf98sCxkd3dN5coaOQQ-s0A7PtrcDZY7hktQDvApjzLCCnP73IEB6IGSRrZ06g6rm96UpAyfkDM0pClrByjLuRxDHFkOXUHwNMBCglZFCkkezwYAY1pT4zb1CVY6l2oN1ewax9xNd-ASTTdiiRY3rNJQMGzu4EbdQ_SANpd-044RO0M3Ncbahgyx04S4VFuelyPzOmwglEJtCcX2S_bcEHZwFLqbJJ-JkINYj3LMQ3-NWka6xlV1ifa1mm535HFrc888Vmma0sXgyqOWo-ZytsCPqkqaPWZp1i2P9oYQuZrBUkCENy2H38kIIm8o4hcmfvcUxThYWy9X2pbSBTJb1n7mLwZqudP0OtGZrt5seV1vKinhsxGzI7bYswYdE9xp3XC_4yHZJxxo2zKyeFzkx_sh6eJUb-Sj6PXDqrntreBe3UqJals7BU3Z5Sl-tqz-oCKnS7yNTMBI6hDR-6UcayIRsXQZnDk0xAKYoi8hvQppqVCjrmiOVGbbmJrYPo8cIto5lhhygyqHVb1gJYh4tToxp471hVwb0LNElwK6EcF1S3gLwVA3_cKAScLSKqeCGJS-IpdOrI-AMIAIqhCc5PJG63tLJuSDGAmOHvILsdrCIr0oe4iUnkvd0fdtQTmDQivqFkI2HLcNGBYqYay5mm51hn17D0oyd4UYIQyrN5-bgCfbbI9haKMX7QlVrMHgosCkXC6niBNidyeSUM2stA2zXomi3qtVL4-fxFfa5Ngh2PKQUE1QAo5xJHK5OlSm47atxx8NW990qV54EmazXPYs3zvHK0ybxsnTksqlm1rcjj1uFJR0bR20UiAjV-EiuOQV-xwkkpdGWSMuTgEmwBDukjokKNtKysngTlMYnPCLfWlDrCRskDMQT4mCO4R7ai-NVCsHDoI7ReD6lJBwca-3F1sR6FxaRJsASw-Hi0HJLv5c6JbNHiohCraUSgtqw-xFdNjxOYexFsUzbrShMw2l_YJjVIVO2S7hi8yZ_iWajwXjptfqnWX_eJjqz9vbS_J9Ak9lE_5UWb-9zJfEy_yDaYDfMmk3csgMmS2JGflDCkAcj_wXBEE-qc_iPbu7RQimijvlZN3Du9ls9m43GmZudZ15Y7K0WH4lqK8YES_Ir9S4O779SuIfiz9JfHiZf3-Cp-iPg8LjST_Q2C1-dTPSbD3DkdHq-9aP4_RxZqdF7D3BY-yY9DnPH-dpNvWDcr5-nb_feL5ejTV5_tFs5mt8Wnj-uQ7n68CNS_9x7t_TCBh9NnWqqn1fjftMVZ2_n31vvq6K2n97-xs), [jpg](https://satori-playground-git-fork-sahithyandev-fix-background-i-7197fe.vercel.sh/?share=ZVfprus2kn6Vg9MYZAa6E8myLNmnkwDUvliStVvC_dHa9321g7x7y3dLOk2AEllFflVksciq39_DNorfP95_ifLlc_P2Nk6PKv71999f7be3LM7TbPp4--mAIP_z06evxDWPpuxvtCgfu8p_7NSkirfv1Febzoc4nPK22XlhW811853rV3naCFNcjy9W3Ezx8J1VzOOUJw-q3YnNS_5_sgM_LNOhnZuIaqt22Pn_SJLkh9R9lpE_44-3I_oXkvNtLTiC_BeMUPvpPv5f81D9b-RP_kf-IsBFF6f_DPwxxrFP8KWAMQA0o_REPQUk0MDe2_-AhuEUJBp6mUJerMKjUnkUmccG2Yec3VzvYuX-4N1gdKWYfSKzA3yvHJlae015cg15CqwipZV7XU0aYPKrMhtjMeCssSQTs5tlsxuW8_oYCXlbiUaLyIXO6OxK_gVzry5Hai5HgfCFK9DghVmKNCnLdLq-qsnomkZvwGJ07M7q1p3PhYjbkFzKrUoqtIfC6Mz9BlOAZATApMAAMimkgGI0hmY0Ht4ACPZd2FV-idxbfxaOXDWWAgIACewDkH7j08lRsJStEyUfju1YcphauVfFjcqu4kBHuHavx_zsFS7sBhfNOKOkWMTA4C5thkEXkSoXF7rc1fQg2ksJW1vOecEh3wrblQJ5rR3fC2gNP9FkrYiiaQ7wS0dvl01_2ZL_LCyZhhQJdpuku6Ka8EXDe6cqEV6Rhla0oQh5p_HkJ9ZcHNpOYfBnBa_0C9P9hvk3SMDse07_WPM-EAAyc5j2FJ8f0lND0rkJD4t2DFNFV7Hx_sLKd5Tve0iSf2LSJBB2HRl-x9IYXbCELPmm6-sIpQByXTBKurng5aZe0tw7TMUS1xCFocux0Q5QL0t3YR7GzGOZ9VZz-hUI4dR49VhEjUogitKwrXI0gnzAW95aGp61WHOekTrrJm5S5qontIubZOTAMw_GW_GMGB-rnl2Iq8-Fh7EnluzS23U1-W1znNnW9qu-b5PCbu2bsw1Q4jlbLSCIp3L4iq7Bchz6zr48PU7EtN6h4iIiLsTcO34cRqcT09tFeNgyWKzxGZ2DBg8a0AWWUXanOTWfijaYLewbqYkc1IO5uAHo3NYM26TF-Z4IQEzUePBE7WnwuBy5j8PkqvgQQz3h0TCgAxjc_GtDNP2MJjCQDyzRLp6Fr9XBc2M8QFS7v0Yn-eZwh_V8MHiXzy-0bmEEVI54ON9RZzrPC7d1Fn-SsA2zhONyi29inNyXk-QegIUhTruPuugLS84ntOE1q_LM_IEzXVVflBLUWgl8pH8eMqgQ50TtifsKT_l8VnqfCqFbslUQfE56k_ZruKFzlTsTuwlpCHXGgXb0WUvHWbGENYfUmS2tjB_D3rWghy7Xu90XOiHNwCWeqQ9fueu1PFaHtM9z4XaEzxpQsv1kpQy9f-j9rO5n61vR9isCaDqpA0MoWN11mYd2ZziWYvMxkwutVPPRFp-dwhsIxP84h5R5Bt3aXzexAzm8jXIzSrPH40zD9VhptlRopV7MoS0kELbA6zPJdVPFcoYvMpqKNeXtDKY77iDmMgoGF9VB24PyoJaHRU5jVacrx8I7JJsw6_ow1FDq8-F0rUUe5QVaeEwHe6UkUfZUqFFrWloftH601ifUYbR1gjYkCTahh5yj1FbejAld_kCVtdhgqVrpuZg7tXv0x93WZfMUgzToiJE2G4I32OXKPfZ5u9XseSUPyjxTD-9U5NKtKN0COU_aOj3pwNQvNqMVMOCN7HK4KoEuJXVOM7CjaBCe17Pr3J5G5vAIl1WBz52qEpfcgocIvMBEYOI-MaLRKWAyceNEuT2yzl06DVd9A1XHna1iDMft4DmqBQZhyYvIrBz27i3Xx0mgn7WsY3pM9fPua3xaujRy7inovHbc6LkeNV2FMT6gaD96iozSKp5u6Nk60UKSDwOZ6yaixNtVWFW65mIaXw_x9vTgeoGz-2g8RzN1s6aB0qtdiK2_6shdriY-KMfTytrX4jrGaXslnmqZllIBrrqh8FN0aRR6ewAe6aLD5QBl5z7w2AN4SBtMwSxHMAA5FZ5I87HDQCZ5Hc_b8yRLSBThcgMz2rIwN688LsiBMBOEPcJ9vy6KdOcxw7qg-_0DXaC6kYubIBDqlj4EYRpKNVGeZqBNLqvXPNlg8zHKTe1oPfq4w-oKLV1XaJmtJIozHjpzZZnUHXB2CbCrJCGmjEhws0qea6gxstCLpobY5uRelQdnKDJZinyiNXbpw3tc3U36WbqOzOej1jI6IAhI4y_43dP1lLY5Ts_Oml_Sw4ZyKo0qzjmPDLqwg8ftAFQpFBam7R7xafeW6woOycsnr_p-n6fM_pH3N9v68zX56pMso7mbpQuZULJUqMuFG_L6_tDYVv_dDwUS7H74hJJsHQUivTwwyGmON6SHH6j94J9BH5uYyaSS0jcjkPKyzkOFFPDlxFJach6o8_0edfI0VPlzCwAR0FtHXHRDLfOrUJCVC9Ki1PynDUH6wz6EI3q4VhaUFzN73w27ArVeREa44FtqHUcQ9MYtsb1Wuk6G6hUcjoVYlU1hOE2xMrVHQSuhugge1Enp9V4zWBUeFttwm2sCjOvdz0i05aX2fCsPkWMwWRqlxCCgLBHgzUKpyAncnOHKHCOYQ0YqsBTUx-Z1nLqokdCe2dTVu8QZtIz-dmeuuWIVlcU_i4SwrxsdZpQjyy48DedDcle2ephVdEqRQT7e-mSV1lm-sy7EIVyOna0Mn-NIzQ3hYUicnbVp4QpDHmQw74TePNh84RKibWL-Vg18fDS0p7xaDVKPdjYmObZBSLarixIRwV9uMLxfmK0OgEDt9t5jD4v9S-iwxwAaYDTLEEzmYTl7lLVpeWixRtjyJHxp9yBhv7c1BgYSSxJjRlxkH_KWMyCruLEG3JGUuE36mHBxAccjzb5s1THDOkueNPIO-7f99EllWuic5ZJOv-mpr6YOLD7k6WIlj3BkcvbiWSJkw3E4bEiBFiJovJWK4pnSTU7UT8Zi5yi-OA6e8me6cHA0p7BDFcecSQgJ8LxFs--2SB-FY0MfrTJnDQuP9C6Jwt36xejsr7AYmoUwFc-J8JjSlthOVISWuwfihPL1zY2pAtmDoV7TDErGjuUgDzlnZRleRufpqdxzOQfB5Twer-xI1InLpy0BEhq-lL_-379egf0ff3xufns1fhmX9C8py6-f34nT5_evlCWPV7LddhryhrwRpzf8ByvJq2qn_wNBkO-k71nRW-0Paf5KZV5zuu2nL8Le3r6I2wV2_pS9Rftk-Uj8fLr8jJ6qI_7zZUfH-J9x7Gvn_3Hs-fn9t1_g1-ivisK7pl9bexr2d2lm2328Ycgu6jc-rqr205vTDlX0C7yP3Sd9_79_em-7V6I1vn_8_v5lxe8f5z3Zef-axb1_YK9OFAdz-v6R-NUYf3qP67bIzUf3SgGn9Utvx3mlS0wdxNH7xzTM8R9__Bs), [gif](https://satori-playground-git-fork-sahithyandev-fix-background-i-7197fe.vercel.sh/?share=xVXbjqNGEP0Vi1W0iZgM2MaAndmRuNlcfANssNE8LDc32A2NuRpG8-_BM5nVZvMB6ZeuOqeqTjUSVa-Yj4IQm2FPQVy_pINBUbYw_Pb6ercHgyiMQVTOBl-HJPnb14cPsImDMvoFC-Iig27boycY3j7Ruy3GeeiXMUp7zkewStJP1oUxSJUyTIo7FaZlmH9S56oo41MroB5M7_r_pj3Xv4AcVWkgIIjynv9yOp1-qPZZZtyFs8F49BNk__MWmiT_U0ZJXNDHf69y-Hvglu4svgMEiE9_eW4R0tSDQcLFRoSRyfEKt95z72fhzDmZX_MH3pBkaAsp9BVlHYpojVbKLZWoG6mrTr1QHWKvTinZwZdHLeGUfKOqzCYGy9bQmLY6s66zWrmTlMXjtU_M82ly3ZSpUeNat8WXfoe3jI53aEwcJHN76BiCWO1OBEE0H238L0eQJzy31-7m8h3ov4sE-tsjdIVvTKFxz5Sw9Qt4UTJCv6q7Yz6_BiTd2mE1pEtcSIOu2SST7WW69VnLq5feds6cEHmiD3F-cs41ja9xsB8WAFlLB7mqPBK0GFbr2MquIpB4MaX3MMlK10ksOI7DJIGGG1XWlZO8QAuza1a2DtdWnH4jC5oeZVJ0lT3Tkm0cr9kFYyRoVzfSzmMTols5vuvFZJXk-8pmZBd4Gp8QQT3Fm9OC0aBNpJxNmG6YZxO8g25FJGyQCT5xIKfEmSZCimPqayrOJ3x42AqkkctdUPjrBd5knjLaGXBuSlefPGqLHQ_ls3RdkGZumzeoXiR0GeaZJdr2zrpCuzsuVPPqLVVX5UgfTgoSJcRkFG3rvW_mJiLdtXJpUZBUstDp1METvCtSBQ4A38o2nrPfLHgOaEhSO3ZfL3xO1zfyxaSapVdGuVMo3a0BkhjlVDlU5My4MX49puZnY4uCLR83c1byVxJ_9BWuGTfKUlmI4LJCx8TS5a0iHkVJEXlw0RVBP-5OiKODTaTaot7wiRSxLmqXJsNFjgWmLuXjdVh7kNeA1k7GtpGoydgP6LpgJcO77oVcl47nS52eFxKX6_kysaqMsREf4Qm7MTuK37XMND66rmkDxCes2yC1S8dswY6WY4tVlXkEcqsS-WDOrgJjvpwHF2od83ligEM0v2TKCRy3W-PGFkftPKREOLH8jTqPjOO1HNmLCJIsuZEmYmMeDANZgsjHGlCBg2uqI5ugURCvibx9QO3F1yVhHi-BJeqTLJN4rs1pVedEIVO7W9QctgrHBTTQwYoTt_2_Gw1VZiVHe1jv17fQlpbp0BEuTtwkkZLYMgVC19I3lMFzHPPH9_tMent7SZ_vxlNRg5-m7bcXjJm8YB9IHYcNj249Rg7IATMZ0D-oUwxhj38h [...]

2022-11-15 10:47 UTC, wei commented on src/handler/image.ts
> +        imageSize = parseSvgImageSize(src, atob(imageData))
data uris are not always in base64, are there ways to intelligently detect it?

e.g. 
[Valid data uri `data:image/svg+xml,...` <img width="1773" alt="image" src="https://user-images.githubusercontent.com/5880908/201897809-19ccd959-415f-46d0-8c01-43017c8a7467.png">](https://satori-playground-git-fork-sahithyandev-fix-background-i-7197fe.vercel.sh/?share=pVRbT9swFP4rllHEpjXGsXNpI0DaChE88DQkXvpASNzWzE2iJKUtVf_7znESVtikaZra2Mffd66-nD3NylzRmJ7n-mVWENK0O6Mu9nuUCVkqvVi2MTn1OHdORx240Xm7_IDluqlMugN0btR2QFG-0rXKWl0WwGWlWa-KgU2NXhS3rVo1SKmiVfVAPa-bVs930xLAAuO_p5_S7MeiLtdFPi1NWQN_Mp_P36KC1Xf9qmIixRH00NcScv6bm9tVugD9x3VtPuVpm8YagbPmZfFluzIjR05BdASHRdE48soRYtm2lSO_OiKB_2azYRvJyhqUEsFhY0RiLQQYvWi1-VZuOzNgkOUy7AfhyGvwX6XtEpC5NqZTdIRMkunU72Sed-idtfPGGfqYsInvuWPGg4kFXW_czUhgHAA6GgVvPEUjWKOLfkLEWvHMejuGepXeqU0j6ZJVxuiqUR_zDUM_QHPMN-vr9TwW9MiuR8SA1L3OL6BXCXrg38MJ___D_ekojmMNR2E3RojMlSwU0u53yLiIXOYL4cKeuyyMJi7zpOeiHbejleDDA4JkJxCa2-PDvUchZL4l7Tl4LvIwIQMOXI9JAe7AqYAV_NgkkiyIxm7AZBShstX1Xv9WUpLAzT2uB82EbLCSIRc7u_1o0_etdxhd-72L0l96ef35ER_Y4TArLlE4B_SodVzMaBTMaIf0jwMwTjiJAhK-UZgt4CfwnAZo6E5kldYLjS0FbartqQ1GiA0HAbFekoPxnYxgj5kIjAzZBLz7Nyz0u4Ub-q8zenl-htpdovjiOwna4cdo92UVE59DqMsbuJLliDyUtcnPz0AXjIaZjmhZYcNraLyntmIaj6Hp0K6b0tjHRa6e1gsaz1PTqBFVq_JZ3-8qbMXtxq7AD7at69WTymnc1mt1OPwE)

[Valid data uri `data:image/svg+xml;utf8,...` ](https://satori-playground-git-fork-sahithyandev-fix-background-i-7197fe.vercel.sh/?share=pVRbT9swFP4rkVHEpjXGsXNps4K0FSJ44GlIvPSBkDitmZtESUpbqv73neMkrLBJ04Ta2Mffd66-nD1Jy0ySiEwz9TwvLKtpd1qe7_coW9ZSqsWyjaxTlzH7dNSBG5W1y3dYpppKJztAcy23A4rypapl2qqyAC4t9XpVDGyi1aK4aeWqQUoWrawH6mndtCrfzUoAC4z_ln5M0p-LulwX2azUZQ38SZ7nr1HB6od6kZEl-BF039cSMPaHm5tVsgD9h3WtP2VJm0QKgbPmefFlu9Jf120-HtliBmubM0CKxhaXNufLtq1s8c3mMfw3mw3dCFrWoBRzBrvDY2PBwehZyc33ctuZAYMsE0E_cFtcgf8qaZeA5ErrTtHmIo5nM6-TWdaht8bOHafoY0InnuuMKfMnBnTccTcjgXEA6GgU3PEMjWCNLvoJEWPFUuPtGOpVeqcmjbhLVmqtqka-zzcIPB_NMd-0r9d1qd8jux7hA1L3Or-BXsXvgf8Px72Ph_vbURzHGo7CbAznqSNowIXZ74AyHjrU49yBPXdoEE4c6grXQTtmRiPBhwcEyU4gNDPHh3uPQkA9Q5pzcB3kYUIGHDguFRzcgVMOK_jRSSioH44dn4owRGWj6778q6Q4hpt7XA-acdFgJUMuZnb60aTvGe8wOuZ7E6W_9OLq8wO-ssNhXlygMAX0qH-cz0noz0mH9I8DMGYxK_St4JXCbAE_gec0QEOLslZJvVDYV9Cm2p6aYJZlwkFArNfKwPhWhLDHlPtaBHQC3r1rGnjdwgm8lzm5mJ6hdpcoPvtOgp74PtpdWUWWxyDUxTVcyXJk3Ze1zqZnoAtGw0xGpKyw6zUk2hNTMYnG0HlI11JJ5OEik4_rBYnyRDdyROSqfFJ3uwr7cbsxK_CDvetq9SgzErX1Wh4OvwA)

2022-11-15 12:00 UTC, sahithyandev commented on src/handler/image.ts
> +        imageSize = parseSvgImageSize(src, atob(imageData))
I don't think "adding support for data URIs other than base64" is under this PR's goal.
It would be better to discuss with the authors before start working on your feature request.

2022-11-15 12:15 UTC, wei commented on src/handler/image.ts
> +        imageSize = parseSvgImageSize(src, atob(imageData))
@sahithyandev svg with utf8 data uri is currently supported by the playground when used in an img tag and is broken with changes in this pull request.

[Live Playground (Working)
<img width="1772" alt="image" src="https://user-images.githubusercontent.com/5880908/201917265-b87ecf21-8bfd-47d7-891a-2056327b9fd7.png">](https://og-playground.vercel.app/?share=pVRfb5swEP8qyBPqw4JrbEIS1Fba0qLtYU-r1Je8UDDEHWAEpDSN8t13Z0yWVpOmqQLsu9_v_tnGdyCpziSJyFWmnje143T9vpTXhwPKjrOVqtj2kXPhM-ZezEZwUFm_fYdlqmvKZA9oXsqXCUX5VrUy7ZWugUt1uavqiU1KVdTfe1l1SMm6l-1EPe26XuX7tQawxvxv6cck_VW0eldna13qFvhPeZ6fsoLXT_UqI0fwM-jBriVkzKDH46a-QeFKVYXTten1hmRJn0SqSgp52T0Xn1-qcuaKNYguZ6DUnStuXc63fd-44ovLY3iHYaCDoLoFo5gz2BQeGw8OTs9KDl_1y-gGDLJMhHbgrriD-E3SbwHJVVmOhi4XcbxeB6PMshH9Yfz8ZYoxVnQV-N6SsvnKgJ6_HGckMA8AI42Cv1yjE-gYwk6IGC-WmmjnkDWxQU0Z8VisLEvVdPJ9vWEYzNEd603ten2fzi2ytwifkNba_AGsydwC_5-OBx9P97ejOM81HYXZGM5TT9CQC7PfIWV84dGAcw_23KPhYuVRX_ge-jEzGgk-PCAodgWpmTk-3HsUQhoY0pyD7yEPEzIQwPOp4BAOgnLQ4KGrhaDzxdKbU7FYoLGx9V__taQ4hj_3fD3oxkWHK5lqMbNnR1N-YKLD6JnvTRb704u7DRkbBNwmaBCgjT3kpF6Odw7azanXOFXSFqq-103kBAwu5s03OHY9cx50W2ZXl2ALTtNMZkQ32FA6Eh2IyUWiJVxqMmYiUYBKJh93BYnypOzkjMhKP6n7fYOtrh-MBnGwLdxVjzIjUd_u5PH4Gw)

[Playground from this PR (Not working) 
<img width="1770" alt="image" src="https://user-images.githubusercontent.com/5880908/201917446-128fa5e4-e80b-4112-b59f-d73e578f3e8e.png">
](https://satori-playground-git-fork-sahithyandev-fix-background-i-7197fe.vercel.sh/?share=pVRfb5swEP8qyBPqw4JrbEIS1Fba0qLtYU-r1Je8UDDEHWAEpDSN8t13Z0yWVpOmqQLsu9_v_tnGdyCpziSJyFWmnje143T9vpTXhwPKjrOVqtj2kXPhM-ZezEZwUFm_fYdlqmvKZA9oXsqXCUX5VrUy7ZWugUt1uavqiU1KVdTfe1l1SMm6l-1EPe26XuX7tQawxvxv6cck_VW0eldna13qFvhPeZ6fsoLXT_UqI0fwM-jBriVkzKDH46a-QeFKVYXTten1hmRJn0SqSgp52T0Xn1-qcuaKNYguZ6DUnStuXc63fd-44ovLY3iHYaCDoLoFo5gz2BQeGw8OTs9KDl_1y-gGDLJMhHbgrriD-E3SbwHJVVmOhi4XcbxeB6PMshH9Yfz8ZYoxVnQV-N6SsvnKgJ6_HGckMA8AI42Cv1yjE-gYwk6IGC-WmmjnkDWxQU0Z8VisLEvVdPJ9vWEYzNEd603ten2fzi2ytwifkNba_AGsydwC_5-OBx9P97ejOM81HYXZGM5TT9CQC7PfIWV84dGAcw_23KPhYuVRX_ge-jEzGgk-PCAodgWpmTk-3HsUQhoY0pyD7yEPEzIQwPOp4BAOgnLQ4KGrhaDzxdKbU7FYoLGx9V__taQ4hj_3fD3oxkWHK5lqMbNnR1N-YKLD6JnvTRb704u7DRkbBNwmaBCgjT3kpF6Odw7azanXOFXSFqq-103kBAwu5s03OHY9cx50W2ZXl2ALTtNMZkQ32FA6Eh2IyUWiJVxqMmYiUYBKJh93BYnypOzkjMhKP6n7fYOtrh-MBnGwLdxVjzIjUd_u5PH4Gw)

2022-11-15 12:18 UTC, sahithyandev commented on src/handler/image.ts
> +        imageSize = parseSvgImageSize(src, atob(imageData))
Oops, sorry about that. will fix it soon :)

2022-11-15 12:45 UTC, wei commented on src/handler/image.ts
> +        imageSize = parseSvgImageSize(src, atob(imageData))
Awesome!! 😄 👏

2022-11-15 16:32 UTC, sahithyandev commented on src/handler/image.ts
> +        imageSize = parseSvgImageSize(src, atob(imageData))
Now fixed, I hope.

2022-11-18 17:54 UTC, shuding reviewed
Great PR, thank you! Could you also add some tests?

2022-11-19 00:49 UTC, sahithyandev commented
@shuding Yeah, sure.

2022-11-19 01:17 UTC, sahithyandev commented
I have added the tests. Let me know if any other changes are needed.

2022-11-21 21:14 UTC, shuding commented
Thank you! :)

2022-11-21 21:15 UTC, merged